# Generated by Django 2.2.9 on 2020-03-07 09:38

from django.db import migrations, models
import djongo.models.fields
import ichoose.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller_verification_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_details', djongo.models.fields.EmbeddedField(model_container=ichoose.models.user_details, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('images', djongo.models.fields.ListField(default=[])),
                ('files', djongo.models.fields.ListField(default=[])),
                ('Verification_step_1', models.BooleanField(default=False)),
                ('Verification_step_2', models.BooleanField(default=False)),
                ('Verification_step_3', models.BooleanField(default=False)),
            ],
        ),
    ]
