# Generated by Django 2.2.9 on 2020-01-28 20:38

from django.db import migrations, models
import djongo.models.fields
import ichoose.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_details', djongo.models.fields.EmbeddedField(model_container=ichoose.models.user_details, null=True)),
                ('wishlist', djongo.models.fields.ListField(default=[])),
                ('add_to_cart', djongo.models.fields.ListField(default=[])),
                ('orders', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.orders_buyers)),
                ('customization_requests', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.customization_request_buyers)),
                ('ratings_comments', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.rating_comments_buyers)),
            ],
        ),
        migrations.CreateModel(
            name='loan_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loner_details', djongo.models.fields.EmbeddedField(model_container=ichoose.models.user_details, null=True)),
                ('loan_amount', models.IntegerField()),
                ('intrest_amount', models.IntegerField()),
                ('requirements', models.TextField()),
                ('terms_and_conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='loaners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaner_details', djongo.models.fields.EmbeddedField(model_container=ichoose.models.user_details, null=True)),
                ('posted_loans', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.loan_details)),
                ('loans_accepted', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.loan_details)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_details', djongo.models.fields.EmbeddedField(model_container=ichoose.models.user_details, null=True)),
                ('product_title', models.TextField()),
                ('category_1', models.TextField()),
                ('category_2', models.TextField()),
                ('product_description', models.TextField()),
                ('product_quantity_available', djongo.models.fields.ListField(default=[])),
                ('product_customisation_available', djongo.models.fields.ListField(default=[])),
                ('orders', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.orders_products)),
                ('ratings_comments', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.rating_comments_products)),
                ('date_of_post', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_details', djongo.models.fields.EmbeddedField(model_container=ichoose.models.user_details, null=True)),
                ('posted_products', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.product)),
                ('product_orders', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.orders_sellers)),
                ('loans_applied', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.loan_details)),
                ('loans_accepted', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.loan_details)),
                ('verification_status', models.BooleanField(default=False)),
                ('verification_data', models.FileField(upload_to='')),
                ('customization_requests', djongo.models.fields.ArrayField(default=[], model_container=ichoose.models.customization_request_sellers)),
            ],
        ),
    ]
