# Generated by Django 2.2.9 on 2020-03-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ichoose', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellers',
            name='posted_products',
        ),
    ]
